### PR TITLE
filter out empty results in serialization, not in db

### PR DESCRIPTION
**Pull request by simpleauthority**

### CODE REVIEW

**Comment by simpleauthority** [comment]
fixes #17

**Comment by LaxWasHere** [comment]
This PR has my 👍 @md-5

**Comment by darbyjack** [comment]
This PR is clear for takeoff. Merge merge merge!

**Comment by md-5** [comment]
Relatedly though, putting a , in your identity blows things up

**Comment by simpleauthority** [comment]
> Relatedly though, putting a , in your identity blows things up

oh lord, ok, next pr

**Pull request merged**
