### PR TITLE
clean up Database after PRs,  fix getResourcesByAuthor

### PR DESCRIPTION
**Pull request by simpleauthority**

### CODE REVIEW

**Comment by darbyjack** [comment]
Looks good.

**Comment by md-5** [comment]
I would rather just whitelist /data/ from cloudflare so you can get the avatars there than expose files via the API

**Comment by simpleauthority** [comment]
> I would rather just whitelist /data/ from cloudflare so you can get the avatars there than expose files via the API

That works.

**Comment by darbyjack** [comment]
> I would rather just whitelist /data/ from cloudflare so you can get the avatars there than expose files via the API

Please let us know when this is done. Thank you.

**Comment by simpleauthority** [comment]
removed icon stuff, this pr stands as just clean up and a method fix now

**Pull request closed without merging**
