### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by simpleauthority**
This PR is aiming to fix a few different issues. Changes in following comments.

### CODE REVIEW

**Comment by simpleauthority** [comment]
https://github.com/SpigotMC/XenforoResourceManagerAPI/pull/29/commits/8f76315f307ee37da8db1d91ec441b8617699524 fixes #21

**Comment by simpleauthority** [comment]
https://github.com/SpigotMC/XenforoResourceManagerAPI/pull/29/commits/8f76315f307ee37da8db1d91ec441b8617699524 closes #21

**Comment by simpleauthority** [comment]
Should put #21 to rest finally and close #27.

#27 constitutes a breaking change, so we'll probably want to announce that. It's minor, but could be impactful for those reading identities.

**Comment by md-5** [comment]
lgtm

**Comment by simpleauthority** [comment]
@md-5 works locally for me, so merge at your leisure. Thanks for the check

**Pull request merged**
